# docker run -d -p 127.0.0.1:9200:9200 -p 127.0.0.1:9300:9300 -v "$PWD":/usr/share/elasticsearch/config -v "$PWD":/usr/share/elasticsearch/data -v "$PWD":/usr/share/elasticsearch/logs kylozw/elasticsearch:2.4.0 --name elasticsearch_config
FROM elasticsearch:2.4.0
MAINTAINER Docker kylo <kylo.zw@gmail.com>
